import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'TURBO GTX-35',
    price: 1299.00,
    rating: 4.9,
    category: 'Motor',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAV7ZgkxHUh3i23q07ay4lzqcixsR849oOFUJaoJHZwYdEnvFkCvKrjVxkF826isOdcV0sUlndi5jZTYJP1xm7fJCZMwZFKCnsWr8XGQuuoGjfawViR3fQ3nOcz_C-wNfI_dZt_aDF82QpWREkVOb3VmMQct7fTLsAm70dQot0LtwD9ThR97Gso5aAbbCHvsQx419cXkodBgq743dYhq0JM59ynq2amZXmeAFZfRAtHCiDcJL5ueygLEGEj9X7vlCX617s6uyL4eFFi',
  },
  {
    id: '2',
    name: 'FREIOS DE CARBONO',
    price: 2450.00,
    rating: 4.8,
    category: 'Freios',
    inStock: false,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCcCnOraCSpKNumJONITvMsTkbLGPu-JsusXTK5Fbu2uYYPLTpPJPvgwkzIbuyPyJQUiDAJuKKCjixFb4LFKVD1tFb7zfmYrNfzSxLgkG4BDX_ks1-V5IMTyWK3WzxpRwNFmpkJMB2RSwz0YjoZ3Uw-E5RYkW_ZwsLGrPLrVEysLg8O-LkVaUEm9GQSJXIi_tiqsonfK3ekKrijG7FihKiTyl2qUs8mspJ38JZjZbResyvJ5p_kqa3Kp1rn9tx-l_xXKhmKRxmyqN2p',
  },
  {
    id: '3',
    name: 'SUSPENSÃO ROSCA RACE',
    price: 849.00,
    rating: 4.7,
    category: 'Suspensão',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCsCiOqtEK66khPMzWTlHnm0myFaJwoYFQQHxQln-iiqIARLjgl0vvyNEHx61xpgSSVnwNdlXjMjEXpM8dk7bK9CZ4lBAUOVvDqhOliwWcsTQYWGNa3fMGPrUDJeR126PpqwwjDhkwtwLpVeZrozwdZtkVR0GGOLp6LkPF5Fau4OdCZ85MRQ4hLk-Jqoit1BBKpXra1nvqkCAgt2-85BAp5aA7ZzGOKzdO5f0QvwALlkBhWpdtz1wE7nSq4xMD8NxR-AfZIP9v6KMsh',
  },
  {
    id: '4',
    name: 'COLETOR DE TITÂNIO',
    price: 1120.00,
    rating: 5.0,
    category: 'Escapamento',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD8MKfayZJv_rgcuEQyVAKgBdBdZI_KRbz0kqycylk2ftnlRFlOjT_ZJXuhVVDCqnE-XLw1zwFjgLQlK-s2guw08vNlmM2RyFgw1WnjhXXTfM_Zi7aiVJLqPh9OeL2z7wJ3guntTOreX18Xjl4NgfJbR_hqmTLgcQUCfj3_KAjPrSFUSxeZ1xc-C3e5qf8PAwgQRFSxR_UzfVSQuppXrBPV_IQ4zhFInGFW71f8G844AeBwG0TyOPMezvzJkUCgyPFYCHBLH-CLluUv',
  },
  {
    id: '5',
    name: 'RODAS FORJADAS',
    price: 550.00,
    rating: 4.9,
    category: 'Rodas',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCHcTSfpI_mbEo5ID5PQ9H7s-A_25RZapfihFbgdNrgKE8eZyEuYo735zWlvUX5E1ETzLes15hBmtPW9OobqumFSFpLd8eF4xPiBAJW4dlWpfyG9b-TFYDzB9xIQ9FJwhA0kqYtgzzyBTkUjm-g2RZ_NojVCbmpi3y5FJXFT2cfByBSxsHh_lvfrATDgpIcPvou74yLsCsPnrEUbO04PVnuK4BK9p7VnwYFK5qJ7A56RYXM_nYVglJqZ1kVxQ_3aLVIazYfBtwYRDpL',
  },
  {
    id: '6',
    name: 'ADMISSÃO EM CARBONO',
    price: 399.00,
    rating: 4.6,
    category: 'Motor',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAbsBkTRp8RPvYx2QhtLBSfAOIQm3VC_oQKvxNyrPwQtgrqdgolDe3PgCIZHIOEEi640ulX4Y9WZHLK52uDhdxexC3yLDfXtQH5Q3O1qkZpXjjASvbQ-6pb_aSkmDhG_PBHMWS7-jlQ6-H2myOX9P0q-HoV5iuAXdJX60SioaF_eXi5pQRHJ8v2yKoPck40Yngb0G6-PWdsMppCOq1vyX36FhQuPHrOH655Ft4Nhu5jpq3y0mR-xjEiOWN0-M7J_TmeYsWhmpLgoP60',
  },
  {
    id: '7',
    name: 'PAINEL LCD DIGITAL',
    price: 675.00,
    rating: 4.8,
    category: 'Interior',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDtK4LNwsJd8mJygeOGA-qeYBbTKxSM_ZHEqRireeWmSo9i5Zkp7j5oA3otPhAWD_sJ6T1D5eq4RzQut_udzpPbARgWel-lmC7ej4H2TfGoiepqcFWOwlMh3OIiuM69hD33e68-gYxCo2v948u3LvjbLNW3GgcotbGFoUxuD8eI6rJUANLHbnneGVeEw2N_UxgN_eDDt8Zl_-SUaAjTP5AT-XoIcRK9jVKpwQV8PXID1pDQzpdDyKuiskvKzPAxuUx7zZr_JZ5sowDi',
  },
  {
    id: '8',
    name: 'FILTRO DE ALTO FLUXO',
    price: 85.00,
    rating: 4.5,
    category: 'Motor',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBvyypyFM53912X4mUADpo0RgtUT4i8f7COJzLT07sfam8iDYUorGgnvYniTvP85c-1Md1V0zpfp4tdUbN3nHMxeb7Kdqzr4nSRkFFN0GFHBGTy8tl_D_X7zm0aItRJeeOl2kDpxIQLpgMhz9rKI_7wReADkktRF99hTVr5bQJ5LNEzPOhsACxloFOnIP0bxhry95X495uIGuz_3kREw3PvOI5qniS8ypid9pWlkjr8yd1N_qsFNZiVfXL5Ospbk5D6Z--DMMxtIsd7',
  },
  {
    id: 'mola-mestra',
    name: 'Mola Mestra para Caminhão Pesado',
    price: 0, // Sob consulta
    rating: 5.0,
    category: 'Suspensão',
    inStock: true,
    code: 'MS-4492-R',
    description: 'Sistema de suspensão reforçado em aço silício cromo de alta resistência. Desenvolvido para transporte de carga excedente e terrenos severos.',
    image: 'https://lh3.googleusercontent.com/aida/ADBb0ugE_diZN2_pIwTsvWC3Nx6xTV1d6g9Eus4OBVE3IG7Ksp8U18RDRQrHWNyAJbB2SzLEdbkqbjgWYwDNDxJQZAvU8-A3ovdWmnLYvy490kKHleSfiLC1OAvGsLfc28TTyByYLq4jGJR3a98Z1hl_Cs1aLhIYTcjDsRKOoeubHob7w8XW2EUobpinjmwINHTWon0J1jaF7Pd_GLl4ns5vvYumQ9uXPPb2pz2DRrIrDRHxYLtNBgg6tgx-WzOt',
    specs: [
      { label: 'Capacidade', value: '12.5 Ton' },
      { label: 'Material', value: 'Aço 5160H' },
      { label: 'Comprimento', value: '1.450 mm' },
      { label: 'Largura', value: '90 mm' },
      { label: 'Espessura', value: '18 mm' },
      { label: 'Origem', value: 'Brasil' },
    ]
  }
];
